### ISSUE TITLE
Clicking route makes waze page crash

### ISSUE THREAD

**Issue by WesSec** [r-renato/ha-card-waze-travel-time#11]
Hi,

I just installed your card, and when I click a route to open it in Waze maps (Firefox 77, Win10) the website crashes. It looks like it tries to refresh the page a gazillion times. I cannot find any logs which are related, i hope you can reproduce it. I see the &time=now flickering in the URL bar when the page tries to load, this might be related.

My card config:
```
columns:
  - from
  - to
  - duration
  - distance
destinations:
  - entity: sensor.home_to_work
    from: Home
    to: Work
name: Travel Time
type: 'custom:ha-card-waze-travel-time'
unit: km
```

My sensor:

```
- platform: waze_travel_time
  name: Home to Work
  origin: zone.home
  destination: zone.work
  region: 'EU'
```

Cheers!
