### ISSUE TITLE
Header does not display

### ISSUE THREAD

**Issue by mckochan** [r-renato/ha-card-waze-travel-time#12]
Header showing column label is not showing up

I've tried header: true and just deleting the line as default setting should be true.
Checked both on my computer on Firefox and on my iPhone.

I am on HA 2021.7.4

```
type: custom:ha-card-waze-travel-time
name: Mike to...
header: true
unit: mi
columns:
  - to
  - duration
  - distance
  - route
destinations:
  - entity: sensor.mike_to_home_waze
    from: Mike
    to: Home
  - entity: sensor.mike_to_home_waze_toll
    to: Home (Toll)
  - entity: sensor.mike_to_work_waze
    to: Work
```
