### ISSUE TITLE
"Columns", "from" and "to" not showing

### ISSUE THREAD

**Issue by vitinhosessa** [r-renato/ha-card-waze-travel-time#3]
![waze](https://user-images.githubusercontent.com/41197767/68087998-aa951a00-fe39-11e9-8944-b3e64bd271d3.png)

 My Lovalace config to this card:

````yaml
card:
  header: true
  columns:
    - from
    - to
    - duration
    - distance
    - route
  destinations:
    - entity: sensor.para_metro_cjsp
      name: "Metro Jardim São Paulo"
    - entity: sensor.para_casa_vitao
      name: "Casa Vitão"
  name: Waze
  type: 'custom:ha-card-waze-travel-time'
style:
  background-color: 'rgba(50,50,50,0.3)'
  background-repeat: no-repeat
  background-size: 100% 300px
  border: 'solid 1px rgba(100,100,100,0.3)'
  border-radius: 20px
  box-shadow: '3px 3px rgba(0,0,0,0.4)'
type: 'custom:card-modder'
````

**Comment by r-renato** [comment]
Hi, thanks for the report.
The correct example is the follows:

```yaml
type: custom:card-modder
card:
  type: custom:ha-card-waze-travel-time
  header: false
  name: "Route to..."
  columns:
    - from
    - to
    - duration
    - distance
    - icon
  destinations:
    - entity: sensor.waze_home_1_workplace
      from: "Place 1"
      to: "Place 2"
    - entity: sensor.waze_home_2_workplace
      to: "Place 3"
style:
  background-repeat: no-repeat
  background-color: rgba(50,50,50,0.3)
  background-size: 100% 300px
  border-radius: 20px
  border: solid 1px rgba(100,100,100,0.3)
  box-shadow: 3px 3px rgba(0,0,0,0.4)
```
