### ISSUE TITLE
setConfig is undefined

### ISSUE THREAD

**Issue by Veldkornet** [r-renato/ha-card-waze-travel-time#4]
Card-modder is listed as deprecated in favor of card-mod.

Hence, I tried with card-mod but I get the following:
`r.setConfig is not a function. (In ‘r.setConfig(Object(i.a)(t))’,’r.setConfig’ is undefined`

Assuming that this is because of card-mod, could you consider moving over to that since card-modder is deprecated?

**Comment by r-renato** [comment]
Hi,
I use `Home Assistant 0.99.3` and for me this code working fine:

```
                   type: custom:mod-card
                   style: |
                     ha-card {
                       border: 1px solid green;
                     }
                   card:
                     type: custom:ha-card-waze-travel-time
                     headers: false
                     {% if name is defined %}
                     name: {{ name }}
                     {% endif %}
                     columns:
                       - from
                       - to
                       - duration
                       - distance
                       - icon
                     destinations:
                     {% for e in destinations %}
                     - entity: {{ e.entity }}
                       to: {{ e.to }}
                     {% endfor %}
```

Try to use `ha-card-waze-travel-time` without `mod-card` to see if the issue depend on your `ha` version.
