### ISSUE TITLE
Card is blank

### ISSUE THREAD

**Issue by riddledaxis** [r-renato/ha-card-waze-travel-time#6]
I am using HassOS v3.12 and HA v0.107.5 although issue happened on 0.106 and the HACS HA (Lovelace) Card Waze Travel Time version is 16af755

The issue is that my Lovelace card  shows a white box with no routes

My Waze sensor config is as follows:
```
sensor:
  - platform: waze_travel_time
    name: "To Work"
    origin: Zone.home
    destination: zone.paul_work
    realtime: true
    region: 'EU'
  - platform: waze_travel_time
    name: "To Home"
    origin: Zone.paul.work
    destination: zone.home
    realtime: true
    region: 'EU'
```

My Lovelace card config is
```
type: 'custom:ha-card-waze-travel-time'
header: false
name: Route to...
unit: mi
columns:
  - from
  - to
  - duration
  - distance
  - icon
destinations:
  - entity: sensor.to_work
    from: Home
    to: Work
  - entity: sensor.to_home
    to: Home
style: |
  ha-card: {
  background-repeat: no-repeat
  background-color: 'rgba(50,50,50,0.3)'
  background-size: 100% 300px
  border-radius: 20px
  border: 'solid 1px rgba(100,100,100,0.3)'
  box-shadow: '3px 3px rgba(0,0,0,0.4)'
  }
```
I originally tried to use custom: card-modder, but switched to HACS integration cad-mod after I got an invalid config warning and it was suggested to use this.

![waze card route](https://user-images.githubusercontent.com/47009467/77259122-47d0dd80-6c77-11ea-9679-358a6ff4e82a.png)

Any idea what I am doing wrong?

Thanks

Paul
