### ISSUE TITLE
Error on retrieving data: empty response

### ISSUE THREAD

**Issue by GitHubxtsnl** [r-renato/ha-card-waze-travel-time#9]
running HA 0.109.6
on a Pi4

I'm getting the message below in my HA log after a restart of HA.

-----------
Log Details (WARNING)
Logger: homeassistant.components.waze_travel_time.sensor
Source: components/waze_travel_time/sensor.py:120
Integration: waze_travel_time (documentation, issues)
First occurred: 8:51:15 PM (1 occurrences)
Last logged: 8:51:15 PM

Error on retrieving data: empty response
------------

```
sensor:
  - platform: waze_travel_time
    origin: !secret waze_origin
    destination: !secret waze_destination
    name: home2work
    region: 'EU'
    realtime: true
    vehicle_type: car
    avoid_ferries: true
    avoid_toll_roads: true
    avoid_subscription_roads: true
# TO HOME FROM WORK
  - platform: waze_travel_time
    origin: !secret waze_destination
    destination: !secret waze_origin
    name: work2home
    region: 'EU'
    realtime: true
    vehicle_type: car
    avoid_ferries: true
    avoid_toll_roads: true
    avoid_subscription_roads: true
```
